Merged release.json and project.json into one file, renamed bin/release.sh to bin/increment-version and its now using jq

diff --git a/nubis/bin/increment-version b/nubis/bin/increment-version
--- a/nubis/bin/increment-version
+++ b/nubis/bin/increment-version
@@ -1,63 +1,89 @@
 #!/bin/bash
 #
-# This script will bump the build and/or the release numbers in $file, which is
-# a json file that's consumed by packer. It's currently called from the Makefile
-# to do this for you, allowing you to build a series of AMIs quickly without
-# an additional step.
+# This script will bump the build and/or the release numbers in the project json file,
+# which is consumed by packer. This script is currently called by make which allows you
+# to quickly build a series of AMIs quickly without an additional step.
 #
 
 usage(){
-   echo "Usage: $0 -f|--file <file> [-r|--release]" 1>&2
+   if [[ $# -gt 0 ]]; then
+      echo "$@"
+      echo
+   fi
+
+   echo "Usage: $0 --file <path to project.json> [--release] [--build]"
    echo
-   echo "Script is invoked automagically via make, but open me up and read"
-   echo "comments for more information."
+   echo "This script will increment either the build or release variable inside a json file."
+   echo
+   echo "Increment the release number, and set the build version to 1:"
+   echo "$0 --file project.json --release"
+   echo
+   echo "Increment the build number:"
+   echo "$0 --file project.json --build"
+   echo
    exit 1
 }
 
+fail(){
+   echo "$@"
+   echo
+   exit 1
+}
+
+hash jq 2>/dev/null || fail "Please install jq to use this build tool. https://github.com/stedolan/jq"
+
+increment_release=0
+increment_build=0
+
 while [[ ! -z "$1" ]]; do
    case "$1" in
-      -f | --file )
-         file="$2"
+      --file)
+         if [[ "$2" ]]; then
+            if [[ -r "$2" ]]; then
+               file="$2"
+            else
+               fail "File $2 is unreadable"
+            fi
+         else
+            fail "Must pass parameter to --file"
+         fi
          shift
          ;;
-      -r | --release )
+      --release)
          increment_release=1
          ;;
+      --build)
+         increment_build=1
+         ;;
       *)
-         echo wtf $1
-         usage
+         usage "Invalid option $1"
     esac
     shift
 done
 
-# Required argument.
-if [[ -z "$file" ]]; then
-echo erp
-   usage
-fi
-
 umask 077
-if [ -f $file ]; then
-   # Poor mans json parsing
-   release=$(grep release $file | cut -d ':' -f 2 | cut -d '"' -f 2)
-   build=$(grep build $file | cut -d ':' -f 2 | cut -d '"' -f 2)
+if [[ $increment_release -eq 1 ]]; then
+   tmp_json_file=$(mktemp ${file}.XXXXXX)
+   jq '.release = (.release | tonumber | . + 1 | tostring) | .build = (0 | tostring)' < $file > $tmp_json_file
 
-   if [ ${increment_release:-0} -eq 1 ]; then
-      release=$(($release + 1))
-      build=0
+   if [[ -s $tmp_json_file ]]; then
+      mv -f $tmp_json_file $file
    else
-      build=$(($build + 1))
+      rm -f $tmp_json_file
+      fail "Failed to write to $tmp_json_file"
+   fi
+elif [[ $increment_build -eq 1 ]]; then
+   tmp_json_file=$(mktemp ${file}.XXXXXX)
+   jq '.build = (.build | tonumber | . + 1 | tostring)' < $file > $tmp_json_file
+
+   if [[ -s $tmp_json_file ]]; then
+      mv -f $tmp_json_file $file
+   else
+      rm -f $tmp_json_file
+      fail "Failed to write to $tmp_json_file"
    fi
 else
-   release=0
-   build=1
+   fail "You must specify either --build or --release"
 fi
 
-rm -f $file
-# Poor mans json writer
-cat << EOF > $file
-{
-  "release": "$release",
-  "build": "$build"
-}
-EOF
+echo Project is now at $(jq --raw-output '"\(.release).\(.build)"' < $file)
