Catch cURL errors and bail out
Also, retry the user-data API endpoint, in case of transient errors

diff --git a/nubis/puppet/files/nubis-metadata b/nubis/puppet/files/nubis-metadata
--- a/nubis/puppet/files/nubis-metadata
+++ b/nubis/puppet/files/nubis-metadata
@@ -7,7 +7,13 @@ if [ ! -d "$(dirname $USERDATA_FILE)" ]; then
 fi
 
 # the -z flag lets us do a conditionnal get if-modified-since
-curl -fqs -z $USERDATA_FILE -o $USERDATA_FILE http://169.254.169.254/latest/user-data
+curl --retry 5 -fqs -z $USERDATA_FILE -o $USERDATA_FILE http://169.254.169.254/latest/user-data
+
+CURL_RV=$?
+if [ "$CURL_RV" != "0" ]; then
+  echo "ERROR: curl failed! ($CURL_RV)"
+  exit $CURL_RV
+fi
 
 if [ "$1" ]; then
   source $USERDATA_FILE
